<?php declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */

$cateImage = json_encode($block->getViewFileUrl('Evozon_Secondary/images/cate.jpg'));
$dogeImage = json_encode($block->getViewFileUrl('Evozon_Secondary/images/doge.jpg'));
?>

<script type="text/x-magento-init">{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "custom-knockout": {
                    "component": "uiComponent",
                    "children": {
                        "cate": {
                            "component": "Evozon_Secondary/js/viewmodel",
                            "template": "Evozon_Secondary/pixelbg",
                            "image": <?= $cateImage ?>,
                            "displayArea": "groupA"
                        },
                        "doge": {
                            "component": "Evozon_Secondary/js/viewmodel",
                            "template": "Evozon_Secondary/pixelbg",
                            "image": <?= $dogeImage ?>,
                            "displayArea": "groupA"
                        }
                    }
                }
            }
        }
    }
}
</script>

<div data-bind="scope: 'custom-knockout'">
    <!-- ko foreach: getRegion('groupA') -->
    <!-- ko template: getTemplate() --><!-- /ko -->
    <!-- /ko -->
</div>
