<?php declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */

$cateImage = json_encode($block->getViewFileUrl('Evozon_Secondary/images/cate.jpg'));
$dogeImage = json_encode($block->getViewFileUrl('Evozon_Secondary/images/doge.jpg'));
?>

<script type="text/x-magento-init">{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "custom-knockout": {
                    "component": "uiComponent",
                    "children": {
                        "cate": {
                            "component": "Evozon_Secondary/js/viewmodel",
                            "template": "Evozon_Secondary/pixelbg",
                            "image": <?= $cateImage ?>,
                            "displayArea": "groupA"
                        },
                        "doge": {
                            "component": "Evozon_Secondary/js/viewmodel",
                            "template": "Evozon_Secondary/pixelbg",
                            "image": <?= $dogeImage ?>,
                            "displayArea": "groupA"
                        }
                    }
                }
            }
        }
    }
}
</script>

<div data-bind="scope: 'custom-knockout'">
    <!-- ko foreach: getRegion('groupA') -->
    <!-- ko template: getTemplate() --><!-- /ko -->
    <!-- /ko -->
</div>

<script type="text/x-magento-init">{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "virtual-custom-knockout": {
                    "component": "Evozon_Secondary/js/viewmodel"
                }
            }
        }
    }
}
</script>

<div data-bind="scope: 'virtual-custom-knockout'">
    <h3><?= __('Added via virtual element') ?></h3>
    <!-- ko pixelbg: <?= $cateImage ?>, pixelSize: pixelGivenSize -->
    Virtual elementum lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna
    aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
    consequat. 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
    pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim
    id est laborum.
    <!-- /ko -->
</div>

<script type="text/x-magento-init">{
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "virtual-element-custom-knockout": {
                        "component": "Evozon_Secondary/js/viewmodel",
                        "imageUrl": <?= $dogeImage ?>
                    }
                }
            }
        }
    }
</script>
<div data-bind="scope: 'virtual-element-custom-knockout'">
    <!-- ko template: 'Evozon_Secondary/virtual-element-node'--><!-- /ko -->
</div>
