<?php

namespace Evozon\M2Demo\Model\Api\Data;

use Magento\Framework\Api\ExtensibleDataInterface;

interface CustomerFlairInterface extends ExtensibleDataInterface
{
    /**
     * @return void
     */
    public function setId($id);

    /**
     * @return int
     */
    public function getId();

    /**
     * @return string
     */
    public function getNickname(): ?string;

    /**
     * @return void
     */
    public function setNickname(?string $nickname): void;

    /**
     * @return int
     */
    public function getCustomerId(): ?int;

    /**
     * @return void
     */
    public function setCustomerId($customerId): void;

    /**
     * @return string
     */
    public function getMotto(): ?string;

    /**
     * @return void
     */
    public function setMotto(?string $motto): void;

    // add Extension keyword before the interface parameter, so it will be generated by magento
    public function setExtensionAttributes(CustomerFlairExtensionInterface $extensionAttributes);

    // cannot use aliases for return type annotations !important
    /**
     * @return \Evozon\M2Demo\Model\Api\Data\CustomerFlairExtensionInterface
     */
    public function getExtensionAttributes();
}
