<?php declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<?php // Evozon_M2Demo stands here for module_path/frontend/web ?>
<script type="text/x-magento-init">
    {
        "#target" : {
            "Evozon_M2Demo/js/requirejs-example": {
                "base_url": "<?= $escaper->escapeJs($block->getBaseUrl()) ?>"
            }
        }
    }
</script>

<div id="target"></div>
<?php // data-mage-init can be used to target a specific DOM node ?>
<!--<div id="target" data-mage-init='{-->
<!--    "Evozon_M2Demo/js/requirejs-example": {-->
<!--        "base_url": "--><?//= $escaper->escapeJs($block->getBaseUrl()) ?><!--"-->
<!--    }-->
<!--}'></div>-->

<script type="text/x-magento-init">{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "startSimple": {
                    "component": "Evozon_M2Demo/js/plain-view-model",
                    "base_url": "<?= $escaper->escapeJs($block->getBaseUrl()) ?>"
                }
            }
        }
    }
}
</script>
<div data-bind="scope: 'startSimple'">
    <h2 data-bind="text: title"></h2>
    <pre data-bind="text: output"></pre>
</div>

<?php // observable array example ?>
<script type="text/x-magento-init">{
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "startSimpleArray": {
                        "component": "Evozon_M2Demo/js/array-view-model"
                    }
                }
            }
        }
    }
</script>

<div data-bind="scope: 'startSimpleArray'">
    <table data-bind="foreach: exchange_rates">
        <tr>
            <td data-bind="text: currency_to"></td>
            <td data-bind="text: rate"></td>
        </tr>
    </table>
    <?php
    // data can be maneuvered on the console using commands like
    // require('uiRegistry').get('startSimpleArray').exchange_rates.push({currency_to:'EUR', rate:15})
    // require('uiRegistry').get('startSimpleArray').exchange_rates.pop()
    // or, in order to replace a single element,
    // require('uiRegistry').get('startSimpleArray').exchange_rates.array_splice(0, 1, {currency_to:'GBP', rate:12})
    ?>

    <?php // for plain values, the $data variable can be used when iterating ?>
    <table data-bind="foreach: plain_values">
        <tr>
            <td data-bind="text: $data"></td>
        </tr>
    </table>

    <table>
        <tr>
            <td data-bind="i18n: 'Virtual elements'"></td>
        </tr>
        <?php // virtual elements allow us to hide them from the DOM as HTML comments ?>
        <!-- ko foreach: plain_values-->
        <tr>
            <td data-bind="text: $data"></td>
        </tr>
        <!-- /ko -->
    </table>
</div>

<script type="text/x-magento-init">{
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "startSimpleTrack": {
                        "component": "Evozon_M2Demo/js/trackable-view-model"
                    }
                }
            }
        }
    }
</script>
<div data-bind="scope: 'startSimpleTrack'">
    <table>
        <tr>
            <td data-bind="i18n: 'Trackable observables'"></td>
        </tr>
        <?php
        // using ko.track makes all the properties observables by default, but they are no longer functions so updating the values should be done like
        // require('uiRegistry').get('startSimpleTrack').value = 5
        ?>
        <tr>
            <td data-bind="text: label"></td>
            <td data-bind="text: value"></td>
            <td data-bind="text: power()"></td>
        </tr>
    </table>
</div>
