<?php declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<?php // Evozon_M2Demo stands here for module_path/frontend/web ?>
<script type="text/x-magento-init">
    {
        "#target" : {
            "Evozon_M2Demo/js/requirejs-example": {
                "base_url": "<?= $escaper->escapeJs($block->getBaseUrl()) ?>"
            }
        }
    }
</script>

<div id="target"></div>
<?php // data-mage-init can be used to target a specific DOM node ?>
<!--<div id="target" data-mage-init='{-->
<!--    "Evozon_M2Demo/js/requirejs-example": {-->
<!--        "base_url": "--><?//= $escaper->escapeJs($block->getBaseUrl()) ?><!--"-->
<!--    }-->
<!--}'></div>-->

<script type="text/x-magento-init">{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "startSimple": {
                    "component": "Evozon_M2Demo/js/plain-view-model",
                    "base_url": "<?= $escaper->escapeJs($block->getBaseUrl()) ?>"
                }
            }
        }
    }
}
</script>
<div data-bind="scope: 'startSimple'">
    <h2 data-bind="text: title"></h2>
    <pre data-bind="text: output"></pre>
</div>
