<?php declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<script type="text/x-magento-init">
    {
        "#target" : {
            "Evozon_M2Demo/js/requirejs-example": {
                "base_url": "<?= $escaper->escapeJs($block->getBaseUrl()) ?>"
            }
        }
    }
</script>

<?php // data-mage-init can be used to target a specific DOM node ?>
<!--<div id="target" data-mage-init='{-->
<!--    "Evozon_M2Demo/js/requirejs-example": {-->
<!--        "base_url": "--><?//= $escaper->escapeJs($block->getBaseUrl()) ?><!--"-->
<!--    }-->
<!--}'></div>-->
