<?php declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */
?>
<div id="collapsible-id" data-mage-init='{
    "collapsible": {
        "saveState": true,
        "ajaxContent": true
    }
}'>
    <div data-role="title">
        <h3><?= __('Title for collapsible content') ?></h3>
        <?php // trigger needs to be inside title/header, otherwise it doesn't work. also, the title is used by default as a trigger ?>
        <button data-role="trigger">i'm triggered</button>
    </div>
    <div data-role="content"></div>
    <?php // for ajax content, the href tag is needed so the anchor tag is used, by convention ?>
    <a href="<?= $block->getViewFileUrl('Evozon_M2Demo/ajax-content.html')?>" data-ajax="true"></a>
</div>
